# Form implementation generated from reading ui file '/Users/misha/code/trace_selection_gui/app/theme_manager/theme_view.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ThemeView(object):
    def setupUi(self, ThemeView):
        ThemeView.setObjectName("ThemeView")
        ThemeView.resize(177, 97)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=ThemeView)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.themeName = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.themeName.setFont(font)
        self.themeName.setObjectName("themeName")
        self.horizontalLayout.addWidget(self.themeName)
        self.themeToggle = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        self.themeToggle.setStyleSheet("QCheckBox {\n"
"    spacing: 0px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 50px;\n"
"    height: 24px;\n"
"    border-radius: 12px;\n"
"    subcontrol-position: left;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.448276 rgba(123, 254, 183, 255), stop:0.517241 rgba(255, 255, 255, 255));\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.482759 rgba(255, 255, 255, 255), stop:0.492611 rgba(152, 119, 184, 255));\n"
"    border: 2px solid white;\n"
"\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    border: 2px solid rgba(123, 254, 183, 255);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    border: 2px solid rgba(152, 119, 184, 255);\n"
"}")
        self.themeToggle.setText("")
        self.themeToggle.setChecked(False)
        self.themeToggle.setObjectName("themeToggle")
        self.horizontalLayout.addWidget(self.themeToggle)
        self.horizontalLayout.setStretch(0, 5)

        self.retranslateUi(ThemeView)
        QtCore.QMetaObject.connectSlotsByName(ThemeView)

    def retranslateUi(self, ThemeView):
        _translate = QtCore.QCoreApplication.translate
        ThemeView.setWindowTitle(_translate("ThemeView", "Form"))
        self.themeName.setText(_translate("ThemeView", "Appearance"))
