[project]
name = "trace-selection-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "pyqt6>=6.9.1",
    "time_trace_tools",
]

[tool.uv.sources]
time_trace_tools = { git = 'ssh://git@gitlab.com/DulinlabVU/time-trace-tools.git', tag = "v1.1.0"}

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-coverage>=0.0",
    "pytest-qt>=4.5.0",
]

[tool.setuptools]
package-dir = {"" = "app"}

[tool.setuptools.packages.find]
where = ["app"]


[tool.pytest.ini_options]
pythonpath = ["app"]
testpaths = ["tests"]

