[project]
name = "trace-selection-gui"
version = "1.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.5",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.21",
    "numpy>=2.3.2",
    "pyqt6>=6.9.1",
    "time_trace_tools",
]

[tool.uv.sources]
time_trace_tools = { git = "https://github.com/KleinMisha/time-trace-tools.git", branch = "public-repo-misha" }

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-coverage>=0.0",
    "pytest-qt>=4.5.0",
]

[tool.setuptools]
package-dir = {"" = "app"}

[tool.setuptools.packages.find]
where = ["app"]


[tool.pytest.ini_options]
pythonpath = ["app"]
testpaths = ["tests"]

[tool.coverage.run]
omit = ["tests/*"]


