# Form implementation generated from reading ui file '/Users/misha/code/trace_selection_gui/app/item_list/item_list_app_layout.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ItemListWidget(object):
    def setupUi(self, ItemListWidget):
        ItemListWidget.setObjectName("ItemListWidget")
        ItemListWidget.resize(1706, 1297)
        self.GroupContainer = QtWidgets.QGroupBox(parent=ItemListWidget)
        self.GroupContainer.setGeometry(QtCore.QRect(210, 90, 1101, 1021))
        self.GroupContainer.setObjectName("GroupContainer")
        self.list_box = QtWidgets.QListWidget(parent=self.GroupContainer)
        self.list_box.setGeometry(QtCore.QRect(5, 21, 1091, 871))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.list_box.setFont(font)
        self.list_box.setObjectName("list_box")
        self.add_button = QtWidgets.QPushButton(parent=self.GroupContainer)
        self.add_button.setGeometry(QtCore.QRect(750, 940, 113, 32))
        self.add_button.setStyleSheet("/*  background-color: rgb(107, 161, 255);\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 8px;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"*/")
        self.add_button.setObjectName("add_button")
        self.input_label = QtWidgets.QLineEdit(parent=self.GroupContainer)
        self.input_label.setGeometry(QtCore.QRect(70, 930, 671, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input_label.setFont(font)
        self.input_label.setObjectName("input_label")
        self.remove_button = QtWidgets.QPushButton(parent=self.GroupContainer)
        self.remove_button.setGeometry(QtCore.QRect(880, 940, 113, 32))
        self.remove_button.setStyleSheet(" /*background-color: rgb(253, 92, 59);\n"
"  padding: 10px 20px;\n"
"  border: none;\n"
"  border-radius: 8px;\n"
"  cursor: pointer;\n"
"  font-size: 16px; */\n"
"")
        self.remove_button.setObjectName("remove_button")

        self.retranslateUi(ItemListWidget)
        QtCore.QMetaObject.connectSlotsByName(ItemListWidget)

    def retranslateUi(self, ItemListWidget):
        _translate = QtCore.QCoreApplication.translate
        ItemListWidget.setWindowTitle(_translate("ItemListWidget", "Form"))
        self.GroupContainer.setTitle(_translate("ItemListWidget", "GroupBox"))
        self.add_button.setText(_translate("ItemListWidget", "+"))
        self.input_label.setPlaceholderText(_translate("ItemListWidget", "Enter label name "))
        self.remove_button.setText(_translate("ItemListWidget", "-"))
