# Form implementation generated from reading ui file 'app/interactive_plot/plot_view.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InteractivePlot(object):
    def setupUi(self, InteractivePlot):
        InteractivePlot.setObjectName("InteractivePlot")
        InteractivePlot.resize(1706, 1387)
        self.plotContainer = QtWidgets.QFrame(parent=InteractivePlot)
        self.plotContainer.setGeometry(QtCore.QRect(210, 30, 1031, 711))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotContainer.sizePolicy().hasHeightForWidth())
        self.plotContainer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.plotContainer.setFont(font)
        self.plotContainer.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.plotContainer.setObjectName("plotContainer")
        self.plotFrameLayout = QtWidgets.QVBoxLayout(self.plotContainer)
        self.plotFrameLayout.setObjectName("plotFrameLayout")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=InteractivePlot)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 160, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(15, 0, 15, 0)
        self.gridLayout.setHorizontalSpacing(22)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.zPosMinEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.zPosMinEdit.setObjectName("zPosMinEdit")
        self.gridLayout.addWidget(self.zPosMinEdit, 0, 1, 1, 1)
        self.zPosMaxEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.zPosMaxEdit.setObjectName("zPosMaxEdit")
        self.gridLayout.addWidget(self.zPosMaxEdit, 1, 1, 1, 1)
        self.timeMinEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.timeMinEdit.setObjectName("timeMinEdit")
        self.gridLayout.addWidget(self.timeMinEdit, 2, 1, 1, 1)
        self.timeMaxEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.timeMaxEdit.setObjectName("timeMaxEdit")
        self.gridLayout.addWidget(self.timeMaxEdit, 3, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=InteractivePlot)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 410, 160, 83))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lockLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lockLayout.setContentsMargins(0, 0, 0, 0)
        self.lockLayout.setObjectName("lockLayout")
        self.lockToggle = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.lockToggle.setStyleSheet("QCheckBox {\n"
"    spacing: 0px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 100px;\n"
"    height: 50px;\n"
"    border-radius: 25px;\n"
"    border: 2px solid black;\n"
"    subcontrol-position: center; \n"
"}\n"
"\n"
"")
        self.lockToggle.setText("")
        self.lockToggle.setChecked(False)
        self.lockToggle.setObjectName("lockToggle")
        self.lockLayout.addWidget(self.lockToggle)
        self.label_5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.lockLayout.addWidget(self.label_5)
        self.label_5.raise_()
        self.lockToggle.raise_()

        self.retranslateUi(InteractivePlot)
        QtCore.QMetaObject.connectSlotsByName(InteractivePlot)

    def retranslateUi(self, InteractivePlot):
        _translate = QtCore.QCoreApplication.translate
        InteractivePlot.setWindowTitle(_translate("InteractivePlot", "Form"))
        self.label_3.setText(_translate("InteractivePlot", "t min"))
        self.label_4.setText(_translate("InteractivePlot", "t max"))
        self.label.setText(_translate("InteractivePlot", "z min"))
        self.label_2.setText(_translate("InteractivePlot", "z max"))
        self.lockToggle.setShortcut(_translate("InteractivePlot", "Ctrl+L"))
        self.label_5.setText(_translate("InteractivePlot", "       Lock clicks in plot"))
