"""
Protocols for the Controllers of individual components that define everything needed for the MainController to control them.


NOTE: Here you define stripped-down versions of the controllers with only those methods strictly needed for the MainController.
"""

from typing import Callable, Optional, Protocol, runtime_checkable

from app.main_app.main_model import Trace


@runtime_checkable
class ItemListController(Protocol):
    def connect_window_closed_signal(
        self, callback: Callable[[list[str]], None]
    ) -> None: ...

    def show(self) -> None: ...


@runtime_checkable
class InteractivePlotController(Protocol):
    def connect_line_added_to_plot(self, callback: Callable[[float], None]) -> None: ...

    def connect_line_removed_from_plot(self, callback: Callable[[], None]) -> None: ...

    def reset_for_new_trace(
        self, trace: Trace, section_boundaries: list[int]
    ) -> None: ...

    def data_is_loaded(self) -> bool: ...


@runtime_checkable
class LabelPanelController(Protocol):
    def reset_for_new_trace(self, labels_new_trace: list[str]) -> None: ...

    def update_available_labels(self, updated_list: list[str]) -> None: ...

    def get_assigned_labels(self) -> list[str]: ...

    def get_available_labels(self) -> list[str]: ...

    def connect_open_item_list(self, callback: Callable[[], None]) -> None: ...


@runtime_checkable
class SectionsPanelController(Protocol):
    def reset_for_new_trace(
        self, sections_new_trace: dict[tuple[int, int], list[str]]
    ) -> None: ...
    def update_available_labels(self, updated_list: list[str]) -> None: ...

    def get_section_labels(self) -> dict[tuple[int, int], list[str]]: ...

    def get_available_labels(self) -> list[str]: ...

    def set_start_section(self, value: Optional[int]) -> None: ...

    def set_end_section(self, value: Optional[int]) -> None: ...

    def current_section_has_start_frame(self) -> bool: ...

    def current_section_has_end_frame(self) -> bool: ...

    def create_new_section_current_trace(self) -> None: ...

    def remove_last_section_from_current_trace(self) -> None: ...

    def jump_to_section_by_index(self, target: int) -> None: ...

    def get_number_of_sections_current_trace(self) -> int: ...

    def get_current_section_index(self) -> int: ...

    def connect_open_item_list(self, callback: Callable[[], None]) -> None: ...
